import type { Document, ProcessDocument } from "./types"

export const mockDocuments: Document[] = [
  {
    id: "1",
    title: "Pengaruh Teknologi AI dalam Pendidikan Modern",
    creator: "Dr. Ahmad Fauzi",
    keywords: ["AI", "Pendidikan", "Teknologi"],
    doi: "10.1234/syntra.2024.001",
    publishedAt: "2024-03-15",
    createdAt: "2024-02-20",
    status: "published",
  },
  {
    id: "2",
    title: "Analisis Dampak Perubahan Iklim terhadap Pertanian",
    creator: "Prof. Siti Rahayu",
    keywords: ["Iklim", "Pertanian", "Lingkungan"],
    doi: "10.1234/syntra.2024.002",
    publishedAt: "2024-03-10",
    createdAt: "2024-01-15",
    status: "published",
  },
  {
    id: "3",
    title: "Implementasi Machine Learning untuk Prediksi Cuaca",
    creator: "Ir. Budi Santoso",
    keywords: ["Machine Learning", "Cuaca", "Prediksi"],
    doi: "",
    publishedAt: null,
    createdAt: "2024-03-20",
    status: "draft",
  },
  {
    id: "4",
    title: "Studi Komparatif Framework JavaScript Modern",
    creator: "Dr. Lisa Wulandari",
    keywords: ["JavaScript", "Framework", "Web Development"],
    doi: "10.1234/syntra.2024.004",
    publishedAt: null,
    createdAt: "2024-03-18",
    status: "pending",
  },
  {
    id: "5",
    title: "Pemanfaatan Big Data dalam Sektor Kesehatan",
    creator: "Dr. Andi Wijaya",
    keywords: ["Big Data", "Kesehatan", "Analitik"],
    doi: "10.1234/syntra.2024.005",
    publishedAt: "2024-02-28",
    createdAt: "2024-01-10",
    status: "published",
  },
  {
    id: "6",
    title: "Pengembangan Sistem IoT untuk Smart City",
    creator: "Ir. Maya Putri",
    keywords: ["IoT", "Smart City", "Infrastruktur"],
    doi: "",
    publishedAt: null,
    createdAt: "2024-03-22",
    status: "draft",
  },
  {
    id: "7",
    title: "Kajian Keamanan Siber pada Infrastruktur Kritis",
    creator: "Dr. Rudi Hartono",
    keywords: ["Keamanan Siber", "Infrastruktur", "Kritis"],
    doi: "10.1234/syntra.2024.007",
    publishedAt: "2024-03-01",
    createdAt: "2024-02-01",
    status: "published",
  },
  {
    id: "8",
    title: "Optimasi Algoritma untuk Komputasi Terdistribusi",
    creator: "Prof. Dian Sari",
    keywords: ["Algoritma", "Komputasi", "Terdistribusi"],
    doi: "",
    publishedAt: null,
    createdAt: "2024-03-25",
    status: "pending",
  },
]

export const mockProcessDocuments: ProcessDocument[] = [
  {
    id: "p1",
    title: "Pengaruh Teknologi AI dalam Pendidikan Modern",
    creator: "Dr. Ahmad Fauzi",
    uploadedAt: "2026-03-28T05:30:00.000Z",
    progress: 85,
    status: "processing",
  },
  {
    id: "p2",
    title: "Analisis Dampak Perubahan Iklim terhadap Pertanian",
    creator: "Prof. Siti Rahayu",
    uploadedAt: "2026-03-28T05:25:00.000Z",
    progress: 100,
    status: "completed",
  },
  {
    id: "p3",
    title: "Implementasi Machine Learning untuk Prediksi Cuaca",
    creator: "Ir. Budi Santoso",
    uploadedAt: "2026-03-28T05:20:00.000Z",
    progress: 45,
    status: "processing",
  },
  {
    id: "p4",
    title: "Studi Komparatif Framework JavaScript Modern",
    creator: "Dr. Lisa Wulandari",
    uploadedAt: "2026-03-28T05:15:00.000Z",
    progress: 100,
    status: "completed",
  },
  {
    id: "p5",
    title: "Pemanfaatan Big Data dalam Sektor Kesehatan",
    creator: "Dr. Andi Wijaya",
    uploadedAt: "2026-03-28T05:10:00.000Z",
    progress: 30,
    status: "failed",
  },
  {
    id: "p6",
    title: "Pengembangan Sistem IoT untuk Smart City",
    creator: "Ir. Maya Putri",
    uploadedAt: "2026-03-28T05:05:00.000Z",
    progress: 65,
    status: "processing",
  },
  {
    id: "p7",
    title: "Kajian Keamanan Siber pada Infrastruktur Kritis",
    creator: "Dr. Rudi Hartono",
    uploadedAt: "2026-03-28T05:00:00.000Z",
    progress: 100,
    status: "completed",
  },
  {
    id: "p8",
    title: "Optimasi Algoritma untuk Komputasi Terdistribusi",
    creator: "Prof. Dian Sari",
    uploadedAt: "2026-03-28T04:55:00.000Z",
    progress: 90,
    status: "processing",
  },
  {
    id: "p9",
    title: "Penelitian Sistem Keamanan Blockchain",
    creator: "Dr. Eko Prasetyo",
    uploadedAt: "2026-03-28T04:50:00.000Z",
    progress: 100,
    status: "completed",
  },
  {
    id: "p10",
    title: "Analisis Big Data untuk Prediksi Pasar",
    creator: "Prof. Fitri Handayani",
    uploadedAt: "2026-03-28T04:45:00.000Z",
    progress: 20,
    status: "processing",
  },
]
